In [2]:
import pandas
import numpy

In [2]:
numpy.average([1, 2])

1.5

In [3]:
numpy.std([1])

0.0

In [4]:
df = pandas.DataFrame.from_csv('alpha_gamma_experiments.csv')
df

,alpha,avg_total_actions,avg_total_rewards,gamma,std_total_actions,std_total_rewards
0,0.1,1207.0,2800.0,0.1,0.0,0.0
1,0.1,1306.0,2911.0,0.3,0.0,0.0
2,0.1,1183.0,2747.0,0.5,0.0,0.0
3,0.1,1237.0,2816.0,0.7,0.0,0.0
4,0.1,1265.0,2911.0,0.9,0.0,0.0
5,0.3,1278.0,2860.0,0.1,0.0,0.0
6,0.3,1271.0,2855.0,0.3,0.0,0.0
7,0.3,1177.0,2752.0,0.5,0.0,0.0
8,0.3,1236.0,2816.0,0.7,0.0,0.0
9,0.3,1315.0,2901.0,0.9,0.0,0.0
10,0.5,1211.0,2821.0,0.1,0.0,0.0
11,0.5,1352.0,2972.0,0.3,0.0,0.0
12,0.5,1292.0,2862.0,0.5,0.0,0.0
13,0.5,1306.0,2904.0,0.7,0.0,0.0
14,0.5,1284.0,2873.0,0.9,0.0,0.0
15,0.7,1270.0,2872.0,0.1,0.0,0.0
16,0.7,1255.0,2844.0,0.3,0.0,0.0
17,0.7,1212.0,2800.0,0.5,0.0,0.0
18,0.7,1347.0,2968.0,0.7,0.0,0.0
19,0.7,1235.0,2791.0,0.9,0.0,0.0
20,0.9,1259.0,2809.0,0.1,0.0,0.0
21,0.9,1414.0,3039.0,0.3,0.0,0.0
22,0.9,1076.0,2632.0,0.5,0.0,0.0
23,0.9,1280.0,2895.0,0.7,0.0,0.0
24,0.9,1213.0,2790.0,0.9,0.0,0.0

In [5]:
df['reward_per_action'] = df['avg_total_rewards'] / df['avg_total_actions']

In [9]:
df[['alpha', 'gamma', 'reward_per_action']].sort_values(by='reward_per_action', ascending=False)

    alpha  gamma  reward_per_action
22    0.9    0.5           2.446097
7     0.3    0.5           2.338148
10    0.5    0.1           2.329480
2     0.1    0.5           2.322063
0     0.1    0.1           2.319801
17    0.7    0.5           2.310231
4     0.1    0.9           2.301186
24    0.9    0.9           2.300082
8     0.3    0.7           2.278317
3     0.1    0.7           2.276475
16    0.7    0.3           2.266135
23    0.9    0.7           2.261719
15    0.7    0.1           2.261417
19    0.7    0.9           2.259919
6     0.3    0.3           2.246263
5     0.3    0.1           2.237872
14    0.5    0.9           2.237539
20    0.9    0.1           2.231136
1     0.1    0.3           2.228943
13    0.5    0.7           2.223583
12    0.5    0.5           2.215170
9     0.3    0.9           2.206084
18    0.7    0.7           2.203415
11    0.5    0.3           2.198225
21    0.9    0.3           2.149222